// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDikuyLfXXg1U4jB32iW8BWNfCickFFbFU',
    appId: '1:1046431162459:web:3937299491fcacc574df7e',
    messagingSenderId: '1046431162459',
    projectId: 'esacco-flutter-project',
    authDomain: 'esacco-flutter-project.firebaseapp.com',
    storageBucket: 'esacco-flutter-project.appspot.com',
    measurementId: 'G-XJ0YGQ7X45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA4JG9wZc4C8s-4mxKATfHdGxI-R6nQJc',
    appId: '1:1046431162459:android:3a4b6f56ad5740aa74df7e',
    messagingSenderId: '1046431162459',
    projectId: 'esacco-flutter-project',
    storageBucket: 'esacco-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFAV_0S_bwZpYsYrYHotGUSQ3C6Acvi7w',
    appId: '1:1046431162459:ios:4dda8d959ccfd4a274df7e',
    messagingSenderId: '1046431162459',
    projectId: 'esacco-flutter-project',
    storageBucket: 'esacco-flutter-project.appspot.com',
    iosClientId: '1046431162459-jcdqhks3fuhp8lnc84oiavleop713jkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.esacco',
  );
}
